// Mock services data for the prototype
window.APP_DATA = {
  emergency: [
    { id: "e999", name: "Emergency Services", phone: "999", desc: "If you or someone else is in immediate danger.", hours: "24/7", tag: "emergency" },
    { id: "nhs24", name: "NHS 24 Mental Health Hub", phone: "111", desc: "Phone triage. Press option 1 for mental health.", hours: "24/7", tag: "crisis" },
    { id: "samaritans", name: "Samaritans", phone: "116 123", desc: "A listening ear, day or night. Free to call.", hours: "24/7", tag: "crisis" },
    { id: "breathing", name: "Breathing Space", phone: "0800 83 85 87", desc: "For low mood, anxiety, depression. Free, confidential.", hours: "Mon–Thu 6pm–2am · Fri 6pm–Mon 6am", tag: "crisis" },
    { id: "shout", name: "SHOUT", phone: "Text SHOUT to 85258", desc: "Free, confidential text support for anyone in crisis.", hours: "24/7", tag: "text" },
    { id: "childline", name: "Childline", phone: "0800 1111", desc: "For anyone under 19. Talk about anything that's worrying you.", hours: "24/7", tag: "crisis", age: "under 19" },
  ],

  categories: [
    { id: "crisis", name: "Crisis & Urgent", desc: "Help right now — phone, text, walk-in.", icon: "alert" },
    { id: "mental-health", name: "Mental Health", desc: "Anxiety, depression, low mood, ongoing support.", icon: "mind" },
    { id: "addiction", name: "Drugs & Alcohol", desc: "Treatment, harm reduction, recovery.", icon: "leaf" },
    { id: "peer", name: "Peer Support", desc: "AA, NA, SMART Recovery, peer cafés.", icon: "people" },
    { id: "young", name: "Young People", desc: "CAMHS, youth counselling, school-based support.", icon: "spark" },
    { id: "bereavement", name: "Bereavement", desc: "Grief support after a loss.", icon: "heart" },
    { id: "lgbtq", name: "LGBTQ+ Affirming", desc: "Services run by and for LGBTQ+ people.", icon: "flag" },
    { id: "spiritual", name: "Spiritual & Faith", desc: "Chaplaincy and faith-based care.", icon: "spark" },
  ],

  services: [
    {
      id: "edi-crisis",
      name: "Edinburgh Crisis Centre",
      category: "crisis",
      address: "6 Hope Street, Edinburgh EH2 4DA",
      postcode: "EH2",
      lat: 55.952, lng: -3.197,
      phone: "0808 801 0414",
      email: "info@edinburghcrisis.org.uk",
      website: "edinburghcrisis.org.uk",
      hours: { today: "Open 10am – 9pm", week: "Tue–Sat 10am – 9pm · Sun–Mon Closed" },
      openNow: true,
      ageRange: "16+",
      wait: "Walk-in",
      referral: "Self-referral (walk-in)",
      access: ["wheelchair", "interpreter", "service-animals", "quiet-room"],
      noAccess: ["childcare"],
      blurb: "A place where you can go to talk face-to-face with trained staff if you're in mental health crisis. No appointment needed.",
      coverage: "Edinburgh City",
      verified: "15 April 2026",
      stars: 5,
    },
    {
      id: "nhs-mh-hub",
      name: "NHS 24 Mental Health Hub",
      category: "crisis",
      address: "Phone service · Scotland-wide",
      postcode: null,
      phone: "111",
      hours: { today: "24/7", week: "24/7" },
      openNow: true,
      ageRange: "All ages",
      referral: "Direct call",
      access: ["bsl-relay", "interpreter"],
      blurb: "Phone triage. Can refer you to your local crisis team or alternatives. Press option 1 for mental health.",
      coverage: "Scotland-wide",
      verified: "1 May 2026",
      stars: 5,
    },
    {
      id: "cmht-north",
      name: "Community Mental Health Team (North Edinburgh)",
      category: "mental-health",
      address: "Royal Edinburgh Hospital, Morningside Terrace, EH10 5HF",
      postcode: "EH10",
      lat: 55.927, lng: -3.213,
      phone: "0131 537 6000",
      hours: { today: "Open · Mon–Fri 9am – 5pm", week: "Closed weekends" },
      openNow: true,
      ageRange: "18+",
      wait: "10–14 weeks",
      referral: "GP or NHS 24 referral",
      access: ["wheelchair", "interpreter"],
      blurb: "For moderate to serious mental health issues that need ongoing support. Visits at home or in clinic.",
      coverage: "North Edinburgh postcodes",
      verified: "10 March 2026",
      stars: 4,
    },
    {
      id: "pcmht-east",
      name: "Primary Care Mental Health Team (East)",
      category: "mental-health",
      address: "Easter Road Medical Practice, Edinburgh EH7 5RN",
      postcode: "EH7",
      lat: 55.962, lng: -3.169,
      phone: "0131 536 9000",
      hours: { today: "Open · Mon–Fri 9am – 5pm", week: "Closed weekends" },
      openNow: true,
      ageRange: "18+",
      wait: "4–8 weeks",
      referral: "Self-referral welcome",
      access: ["wheelchair", "online-option", "interpreter"],
      blurb: "Talking therapies for low mood and anxiety. You can refer yourself — no GP letter needed.",
      coverage: "East Edinburgh",
      verified: "20 April 2026",
      stars: 5,
    },
    {
      id: "addaction-edi",
      name: "We Are With You — Edinburgh",
      category: "addiction",
      address: "22 Forth Street, Edinburgh EH1 3LH",
      postcode: "EH1",
      lat: 55.958, lng: -3.190,
      phone: "0131 524 1300",
      hours: { today: "Open · Mon–Fri 9am – 5pm", week: "Sat 10am – 1pm · Sun closed" },
      openNow: true,
      ageRange: "16+",
      wait: "Within 1 week",
      referral: "Self-referral or drop-in",
      access: ["wheelchair", "interpreter", "online-option"],
      blurb: "Free, confidential support for anyone affected by drugs, alcohol or mental health. You won't get in trouble.",
      coverage: "Edinburgh & Lothians",
      verified: "2 May 2026",
      stars: 5,
    },
    {
      id: "harm-reduction",
      name: "Edinburgh Harm Reduction Team",
      category: "addiction",
      address: "Spittal Street Centre, EH3 9DU",
      postcode: "EH3",
      lat: 55.946, lng: -3.201,
      phone: "0131 537 8300",
      hours: { today: "Open · Mon–Fri 9.30am – 4.30pm", week: "Closed weekends" },
      openNow: true,
      ageRange: "16+",
      referral: "Drop-in",
      access: ["wheelchair", "needle-exchange", "naloxone"],
      blurb: "Needle exchange, naloxone supply and advice on staying safer if you're using.",
      coverage: "Edinburgh",
      verified: "8 April 2026",
      stars: 4,
    },
    {
      id: "aa-newton",
      name: "AA Meeting · Newton Terrace",
      category: "peer",
      address: "St Catherine's Convent, 4 Lauriston Gardens, EH3 9HH",
      postcode: "EH3",
      lat: 55.945, lng: -3.205,
      phone: "0800 9177 650",
      hours: { today: "Tonight 7pm", week: "Tue 6pm · Wed 7pm · Sat 11am" },
      openNow: false,
      ageRange: "All ages",
      referral: "Just turn up",
      access: ["wheelchair"],
      blurb: "12-step mutual support for alcohol. All welcome. Free.",
      coverage: "Open meeting",
      verified: "5 May 2026",
      stars: 5,
    },
    {
      id: "smart-leith",
      name: "SMART Recovery · Leith",
      category: "peer",
      address: "Leith Community Centre, EH6 5JA",
      postcode: "EH6",
      lat: 55.974, lng: -3.171,
      phone: "—",
      hours: { today: "Thu 7pm", week: "Thursdays 7pm – 8.30pm" },
      openNow: false,
      ageRange: "All ages",
      referral: "Just turn up",
      access: ["wheelchair", "online-option"],
      blurb: "Evidence-based peer support. Tools and skills for changing addictive behaviour.",
      coverage: "Open meeting",
      verified: "1 May 2026",
      stars: 4,
    },
    {
      id: "camhs-edi",
      name: "CAMHS Edinburgh",
      category: "young",
      address: "Royal Hospital for Children & Young People, EH16 4TJ",
      postcode: "EH16",
      lat: 55.920, lng: -3.139,
      phone: "0131 536 0000",
      hours: { today: "Open · Mon–Fri 9am – 5pm", week: "Out of hours via NHS 24" },
      openNow: true,
      ageRange: "5–18",
      wait: "8–16 weeks",
      referral: "GP or school referral",
      access: ["wheelchair", "interpreter", "quiet-room"],
      blurb: "Mental health support for under-18s. Family and school can be involved if you want.",
      coverage: "NHS Lothian",
      verified: "12 April 2026",
      stars: 4,
    },
    {
      id: "cruse",
      name: "Cruse Bereavement Scotland",
      category: "bereavement",
      address: "Riverside House, 502 Gorgie Road, EH11 3AF",
      postcode: "EH11",
      lat: 55.929, lng: -3.249,
      phone: "0808 802 6161",
      hours: { today: "Open · Mon–Thu 9am – 8pm", week: "Fri 9am – 4pm" },
      openNow: true,
      ageRange: "All ages",
      wait: "2–4 weeks",
      referral: "Self-referral",
      access: ["online-option", "phone-counselling"],
      blurb: "Counselling and support if you've lost someone. Recent or years ago — both welcome.",
      coverage: "Scotland-wide",
      verified: "28 April 2026",
      stars: 5,
    },
    {
      id: "lgbt-health",
      name: "LGBT Health & Wellbeing",
      category: "lgbtq",
      address: "9 Howe Street, Edinburgh EH3 6TE",
      postcode: "EH3",
      lat: 55.957, lng: -3.205,
      phone: "0131 564 3970",
      hours: { today: "Open · Mon–Fri 10am – 6pm", week: "Sat 11am – 4pm" },
      openNow: true,
      ageRange: "16+",
      referral: "Self-referral",
      access: ["wheelchair", "online-option", "lgbtq-affirming"],
      blurb: "Counselling, social groups and advocacy for LGBTQ+ people across Scotland.",
      coverage: "Edinburgh & online Scotland-wide",
      verified: "30 April 2026",
      stars: 5,
    },
    {
      id: "castle-craig",
      name: "Castle Craig Residential Rehab",
      category: "addiction",
      address: "Blyth Bridge, West Linton EH46 7DH",
      postcode: "EH46",
      phone: "0808 271 7500",
      hours: { today: "Admissions 24/7", week: "24/7" },
      openNow: true,
      ageRange: "18+",
      wait: "1–3 weeks",
      referral: "Via local ADP",
      access: ["wheelchair", "dual-diagnosis", "long-stay"],
      blurb: "Residential rehab. 4–12 week stays. Apply through your local Alcohol & Drug Partnership.",
      coverage: "Scotland-wide",
      verified: "15 April 2026",
      stars: 5,
    },
  ],

  glossary: [
    { term: "ADP", full: "Alcohol & Drug Partnership", plain: "A team that runs addiction services in your area. They decide which services to fund locally.", example: "I'll contact my local ADP to apply for rehab." },
    { term: "CAMHS", full: "Child & Adolescent Mental Health Services", plain: "Mental health doctors and nurses who work with children and young people under 18.", example: "My 15-year-old was referred to CAMHS for anxiety." },
    { term: "CMHT", full: "Community Mental Health Team", plain: "A team of mental health workers who visit people at home or in clinics. They help with serious mental health problems that need ongoing support.", example: "The CMHT comes to my house every week to check how I'm doing." },
    { term: "CRHT", full: "Crisis Resolution & Home Treatment", plain: "A team that helps people in crisis stay at home instead of going to hospital. They visit regularly and are on call 24/7.", example: "The CRHT helped me get through a crisis without being admitted." },
    { term: "Dual diagnosis", full: "Dual diagnosis", plain: "When someone has both a mental health condition and a problem with drugs or alcohol at the same time.", example: "She has a dual diagnosis — depression and alcohol dependence." },
    { term: "Harm reduction", full: "Harm reduction", plain: "Practical ways to stay safer if you're using drugs or alcohol, without being told to stop.", example: "The harm reduction worker gave me clean needles and naloxone." },
    { term: "ORT", full: "Opioid Replacement Therapy", plain: "Medicine like methadone or buprenorphine that replaces heroin or other opioids, so you don't get withdrawal.", example: "I've been on ORT for six months and feel stable." },
    { term: "PCMHT", full: "Primary Care Mental Health Team", plain: "Mental health workers based in or near GP surgeries. They help with anxiety, low mood and mild-to-moderate problems.", example: "My GP referred me to the PCMHT for some counselling." },
    { term: "Self-referral", full: "Self-referral", plain: "You contact the service yourself. You don't need a GP or anyone else to refer you.", example: "Most addiction services accept self-referral." },
    { term: "Talking therapy", full: "Talking therapy", plain: "A general name for any treatment where you talk to a trained person about what's happening — counselling, CBT, and others.", example: "Talking therapy helped me understand my anxiety." },
  ],
};
